# This is a GitHub App Manifest. These settings will be used by default when
# initially configuring your GitHub App.
#
# NOTE: changing this file will not update your GitHub App settings.
# You must visit github.com/settings/apps/your-app-name to edit them.
#
# Read more about configuring your GitHub App:
# https://probot.github.io/docs/development/#configuring-a-github-app
#
# Read more about GitHub App Manifests:
# https://developer.github.com/apps/building-github-apps/creating-github-apps-from-a-manifest/

# The list of events the GitHub App subscribes to.
default_events:
  - commit_comment
  - issue_comment
  - pull_request_review_comment

# The set of permissions needed by the GitHub App.
default_permissions:
  # Search repositories, list collaborators, and access repository metadata (required).
  # https://developer.github.com/v3/apps/permissions/#metadata-permissions
  metadata: read

  # Repository contents, commits, branches, downloads, releases, and merges.
  # https://developer.github.com/v3/apps/permissions/#permission-on-contents
  contents: read

  # Issues and related comments, assignees, labels, and milestones.
  # https://developer.github.com/v3/apps/permissions/#permission-on-issues
  issues: write

  # Pull requests and related comments, assignees, labels, milestones, and merges.
  # https://developer.github.com/v3/apps/permissions/#permission-on-pull-requests
  pull_requests: write

# The name of the GitHub App. Defaults to the name specified in package.json
name: tom-hanks-as-a-service

# The homepage of your GitHub App.
url: https://thaas.io

# A description of the GitHub App.
description: Tom Hanks As A Service
